package com.receiptmerger.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_theme_light_primary = Color(0xFF006E40)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF84F7CE)
val md_theme_light_onPrimaryContainer = Color(0xFF00210E)
val md_theme_light_secondary = Color(0xFF4F6352)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1F7D4)
val md_theme_light_onSecondaryContainer = Color(0xFF0D2015)
val md_theme_light_tertiary = Color(0xFF386664)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBEA)
val md_theme_light_onTertiaryContainer = Color(0xFF00201F)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF1A1C1A)
val md_theme_light_surface = Color(0xFFFBFDF9)
val md_theme_light_onSurface = Color(0xFF1A1C1A)

// Dark theme colors
val md_theme_dark_primary = Color(0xFF84F7CE)
val md_theme_dark_onPrimary = Color(0xFF00391D)
val md_theme_dark_primaryContainer = Color(0xFF00532D)
val md_theme_dark_onPrimaryContainer = Color(0xFF84F7CE)
val md_theme_dark_secondary = Color(0xFFB5DBB8)
val md_theme_dark_onSecondary = Color(0xFF1F3425)
val md_theme_dark_secondaryContainer = Color(0xFF354B3A)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1F7D4)
val md_theme_dark_tertiary = Color(0xFFA0CFCD)
val md_theme_dark_onTertiary = Color(0xFF0D3736)
val md_theme_dark_tertiaryContainer = Color(0xFF1F4E4C)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCEBEA)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1A1C1A)
val md_theme_dark_onBackground = Color(0xFFE2E3E0)
val md_theme_dark_surface = Color(0xFF1A1C1A)
val md_theme_dark_onSurface = Color(0xFFE2E3E0)
