// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOaJDlm-FQF8x3CBCo_7cK7oqHgJdO1LU',
    appId: '1:1015745574495:web:04575684621deb7428cdea',
    messagingSenderId: '1015745574495',
    projectId: 'quiz-app-461ac',
    authDomain: 'quiz-app-461ac.firebaseapp.com',
    storageBucket: 'quiz-app-461ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Az3Thovwmo3Pb_cXwpiu5gCChTmoWxU',
    appId: '1:1015745574495:android:4fb539c7a0ac9e9428cdea',
    messagingSenderId: '1015745574495',
    projectId: 'quiz-app-461ac',
    storageBucket: 'quiz-app-461ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUveY3iMYvJSYFf2CvDcCSPzTTcML5_ss',
    appId: '1:1015745574495:ios:bcc55930f8ae96e928cdea',
    messagingSenderId: '1015745574495',
    projectId: 'quiz-app-461ac',
    storageBucket: 'quiz-app-461ac.appspot.com',
    iosClientId: '1015745574495-3c0uf0jf7p49f92r1nthck4s4mfanhv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUveY3iMYvJSYFf2CvDcCSPzTTcML5_ss',
    appId: '1:1015745574495:ios:bcc55930f8ae96e928cdea',
    messagingSenderId: '1015745574495',
    projectId: 'quiz-app-461ac',
    storageBucket: 'quiz-app-461ac.appspot.com',
    iosClientId: '1015745574495-3c0uf0jf7p49f92r1nthck4s4mfanhv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
